/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{html,ts}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "tertiary": "#000000",
              "surface-container": "#e5eeff",
              "surface-container-high": "#dce9ff",
              "surface-container-lowest": "#ffffff",
              "outline": "#76777d",
              "primary-fixed": "#e0e7ff",
              "on-error": "#ffffff",
              "secondary-container": "#6cf8bb",
              "background": "#f8f9ff",
              "surface-variant": "#d3e4fe",
              "primary": "#0f172a",
              "on-secondary": "#ffffff",
              "on-error-container": "#93000a",
              "on-tertiary-fixed": "#2a1700",
              "tertiary-fixed-dim": "#ffb95f",
              "on-primary-fixed-variant": "#4f46e5",
              "on-secondary-container": "#00714d",
              "on-tertiary-container": "#b87500",
              "surface-dim": "#cbdbf5",
              "on-primary-container": "#e0e7ff",
              "secondary-fixed-dim": "#4edea3",
              "primary-fixed-dim": "#c7d2fe",
              "error": "#ba1a1a",
              "secondary": "#10b981",
              "surface-container-low": "#eff4ff",
              "tertiary-fixed": "#ffddb8",
              "on-background": "#0b1c30",
              "inverse-primary": "#c7d2fe",
              "surface-tint": "#565e74",
              "outline-variant": "#c6c6cd",
              "on-tertiary-fixed-variant": "#653e00",
              "primary-container": "#131b2e",
              "surface": "#f8f9ff",
              "on-surface": "#0b1c30",
              "surface-container-highest": "#d3e4fe",
              "secondary-fixed": "#6ffbbe",
              "surface-bright": "#f8f9ff",
              "on-tertiary": "#ffffff",
              "inverse-surface": "#213145",
              "on-primary-fixed": "#312e81",
              "error-container": "#ffdad6",
              "on-secondary-fixed-variant": "#005236",
              "on-primary": "#ffffff",
              "on-surface-variant": "#45464d",
              "on-secondary-fixed": "#002113",
              "tertiary-container": "#2a1700",
              "inverse-on-surface": "#eaf1ff",
              "warning": "#f59e0b",
              "success": "#10b981"
          },
          "borderRadius": {
              "DEFAULT": "0.5rem",
              "lg": "0.75rem",
              "xl": "1rem",
              "full": "9999px"
          },
          "spacing": {
              "margin-mobile": "16px",
              "sm": "8px",
              "lg": "24px",
              "max-width": "1200px",
              "base": "4px",
              "xl": "32px",
              "gutter": "16px",
              "md": "16px",
              "margin-desktop": "48px",
              "xs": "4px"
          },
          "fontFamily": {
              "label-sm": ["Inter", "sans-serif"],
              "headline-lg": ["Inter", "sans-serif"],
              "body-lg": ["Inter", "sans-serif"],
              "headline-lg-mobile": ["Inter", "sans-serif"],
              "label-md": ["Inter", "sans-serif"],
              "body-md": ["Inter", "sans-serif"],
              "headline-md": ["Inter", "sans-serif"]
          },
          "fontSize": {
              "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "500" }],
              "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
              "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
              "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
              "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
              "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
          }
      }
  },
  plugins: [],
}
